# Generated by Django 4.0.6 on 2022-07-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.BigIntegerField(blank=True, null=True, verbose_name='id партнера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заявки')),
                ('first_cur', models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('BNB', 'BNB'), ('TRX', 'TRX'), ('USDT', 'USDT'), ('USDC', 'USDC'), ('RUB', 'RUB'), ('EUR', 'EUR'), ('USD', 'USD')], default='BTC', max_length=10, verbose_name='Входящая валюта')),
                ('second_cur', models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('BNB', 'BNB'), ('TRX', 'TRX'), ('USDT', 'USDT'), ('USDC', 'USDC'), ('RUB', 'RUB'), ('EUR', 'EUR'), ('USD', 'USD')], default='BTC', max_length=10, verbose_name='Входящая валюта')),
                ('first_amount', models.BigIntegerField(verbose_name='Сумма')),
                ('city', models.CharField(max_length=500, verbose_name='Город')),
                ('second_amount', models.BigIntegerField(verbose_name='Сумма сделки')),
                ('profit', models.BigIntegerField(verbose_name='Доход партнера руб.')),
                ('status', models.BooleanField(verbose_name='Статус выплаты')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Список сделок',
                'db_table': 'list_deal',
            },
        ),
    ]
