# Generated by Django 4.0.6 on 2022-07-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_list_deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdeal',
            name='first_amount',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='listdeal',
            name='profit',
            field=models.FloatField(verbose_name='Доход партнера руб.'),
        ),
        migrations.AlterField(
            model_name='listdeal',
            name='second_amount',
            field=models.FloatField(verbose_name='Сумма сделки'),
        ),
    ]
