# Generated by Django 4.0.6 on 2022-07-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_list_deal', '0002_alter_listdeal_first_amount_alter_listdeal_profit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listdeal',
            options={'ordering': ['id'], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Список сделок'},
        ),
    ]
