# Generated by Django 4.0.6 on 2022-07-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_list_deal', '0003_alter_listdeal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdeal',
            name='second_cur',
            field=models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('BNB', 'BNB'), ('TRX', 'TRX'), ('USDT', 'USDT'), ('USDC', 'USDC'), ('RUB', 'RUB'), ('EUR', 'EUR'), ('USD', 'USD')], default='BTC', max_length=10, verbose_name='Исходящая валюта'),
        ),
    ]
