# Generated by Django 4.0.6 on 2022-07-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_list_deal', '0004_alter_listdeal_second_cur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listdeal',
            options={'ordering': ['id'], 'verbose_name': 'сделку', 'verbose_name_plural': 'Список сделок'},
        ),
        migrations.AlterField(
            model_name='listdeal',
            name='first_amount',
            field=models.FloatField(verbose_name='Входящая сумма'),
        ),
        migrations.AlterField(
            model_name='listdeal',
            name='second_amount',
            field=models.FloatField(verbose_name='Исходящая сумма'),
        ),
    ]
