# Generated by Django 4.0.6 on 2022-07-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_list_deal', '0005_alter_listdeal_options_alter_listdeal_first_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdeal',
            name='first_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Входящая сумма'),
        ),
        migrations.AlterField(
            model_name='listdeal',
            name='profit',
            field=models.FloatField(blank=True, null=True, verbose_name='Доход партнера руб.'),
        ),
        migrations.AlterField(
            model_name='listdeal',
            name='second_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Исходящая сумма'),
        ),
        migrations.AlterField(
            model_name='listdeal',
            name='status',
            field=models.CharField(choices=[('Новая', 'Новая'), ('Проведена', 'Проведена'), ('Выплачена', 'Выплачена')], default='Новая', max_length=20, verbose_name='Статус выплаты'),
        ),
    ]
