# Generated by Django 4.0.6 on 2022-07-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='partner_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='id партнера'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='TG Токен Бота'),
        ),
    ]
