# Generated by Django 4.0.6 on 2022-07-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crypto', '0003_alter_customuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='TG Токен Бота'),
        ),
    ]
