# Generated by Django 4.0.6 on 2022-07-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crypto', '0005_alter_customuser_options_alter_customuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='operator_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='id оператора'),
        ),
    ]
